INSERT INTO public.question (id, text) VALUES (2, 'Cite 3 choses que tu caches à tes parents');
INSERT INTO public.question (id, text) VALUES (1, 'Cite 3 bonnes raisons de passer par derrière');
INSERT INTO public.question (id, text) VALUES (3, 'Cite 3 choses aussi débiles que de filer une arme à un dépressif');
INSERT INTO public.question (id, text) VALUES (4, 'Cite 3 choses qui n''ont rien à voir ensemble');
INSERT INTO public.question (id, text) VALUES (5, 'Cite 3 choses que tu sais très bien faire');
INSERT INTO public.question (id, text) VALUES (6, 'Donne 3 choses mieux qu''un 90D');
INSERT INTO public.question (id, text) VALUES (7, 'Avoue 3 choses que tu préfères au sexe');
INSERT INTO public.question (id, text) VALUES (9, 'Trouve 3 voitures plus moche qu''un Multipla');
INSERT INTO public.question (id, text) VALUES (10, 'Cite 3 choses que tu ferais avec ton clone');
INSERT INTO public.question (id, text) VALUES (11, 'Cite 3 choses facile à voler dans un magasin');
INSERT INTO public.question (id, text) VALUES (12, 'Trouve 3 raisons de préférer une petite poitrine à une poitrine plus généreuse');
INSERT INTO public.question (id, text) VALUES (13, 'Cite les 3 choses que tu fais si tu deviens président de la République');
INSERT INTO public.question (id, text) VALUES (14, 'Cite 3 raisons de courir nu en forêt');
INSERT INTO public.question (id, text) VALUES (15, 'Cite 3 façons de se débarrasser d''un cadavre');
INSERT INTO public.question (id, text) VALUES (16, 'Cite 3 choses qui sont vraies mais que personne n''ose dire');
INSERT INTO public.question (id, text) VALUES (17, 'Cite 1 secret entre toi et ton voisin de gauche');
INSERT INTO public.question (id, text) VALUES (18, 'Donne 3 bonnes raisons de préférer une brune à une blonde');
INSERT INTO public.question (id, text) VALUES (19, 'Cite 3 oeuvres de grand peintre');
INSERT INTO public.question (id, text) VALUES (20, 'Cite 3 sortes de pizza');
INSERT INTO public.question (id, text) VALUES (21, 'Avoue les 3 choses auxquelles tu penses dans un ascenseur');
INSERT INTO public.question (id, text) VALUES (22, 'Cite 3 lieux où tu peux regarder mais pas toucher');
INSERT INTO public.question (id, text) VALUES (23, 'Cite les 3 premières choses que tu fais si tu gagnes 1 million d''euros');
INSERT INTO public.question (id, text) VALUES (24, 'Cite 3 endroits où mettre une saucisse');
INSERT INTO public.question (id, text) VALUES (25, 'Cite 3 raisons de ne pas être vegan');
INSERT INTO public.question (id, text) VALUES (26, 'Cite 3 mensonges que tu as sorti à ta famille ou tes amis');
INSERT INTO public.question (id, text) VALUES (27, 'Cite 3 raisons d''échanger ton enfant à la maternité');
INSERT INTO public.question (id, text) VALUES (28, 'Donne 3 raisons de préférer le sexe bestial à la version papa dans maman');
INSERT INTO public.question (id, text) VALUES (29, 'Cite 3 mots anglais que tu connais grâce au porno');
INSERT INTO public.question (id, text) VALUES (30, 'Trouve 3 façons d''envoyer chier les témoins de Jéovah');
INSERT INTO public.question (id, text) VALUES (31, 'Cite 3 choses que tu aimes renifler');
INSERT INTO public.question (id, text) VALUES (32, 'Cite 3 choses à ne jamais dire lors d''un premier rendez-vous');
INSERT INTO public.question (id, text) VALUES (33, 'Cite 3 mots qui commencent par un "U"');
INSERT INTO public.question (id, text) VALUES (34, 'Cite 3 animaux de la jungle');
INSERT INTO public.question (id, text) VALUES (35, 'Cite 3 raisons de ne pas être unijambiste');
INSERT INTO public.question (id, text) VALUES (36, 'Cite 3 avantages à être un nain');
INSERT INTO public.question (id, text) VALUES (37, 'Cite 3 destinations de voyage où tu enverrais ton pire ennemie');
INSERT INTO public.question (id, text) VALUES (38, 'Cite 3 raisons de ne pas prêter ta voiture');
INSERT INTO public.question (id, text) VALUES (39, 'Cite 3 raisons de refuser une invitation à sortir');
INSERT INTO public.question (id, text) VALUES (40, 'Cite 3 raisons de refuser une pipe');
INSERT INTO public.question (id, text) VALUES (41, 'Cite 3 raisons de casser un écran de téléphone');
INSERT INTO public.question (id, text) VALUES (42, 'Cite 3 raisons d''être gay');
INSERT INTO public.question (id, text) VALUES (43, 'Cite 3 raisons d''avoir un pote gay');
INSERT INTO public.question (id, text) VALUES (44, 'Cite 3 raisons d''avoir un pote russe');
INSERT INTO public.question (id, text) VALUES (45, 'Cite 3 bonnes raisons de te suicider');
INSERT INTO public.question (id, text) VALUES (46, 'Cite 3 fruits qui commencent par "P"');
INSERT INTO public.question (id, text) VALUES (47, 'Cite 3 fruits ou légumes qui ressemblent à des sexes');
INSERT INTO public.question (id, text) VALUES (48, 'Cite 3 métiers où il faut être habile de ses mains');
INSERT INTO public.question (id, text) VALUES (49, 'Cite 3 raisons de grimper à un arbre');
INSERT INTO public.question (id, text) VALUES (50, 'Cite 3 bonnes raisons d''être gros');
INSERT INTO public.question (id, text) VALUES (51, 'Cite 3 marques de bières');
INSERT INTO public.question (id, text) VALUES (52, 'Cite 3 mots qui n''existe pas');
INSERT INTO public.question (id, text) VALUES (53, 'Cite 3 choses plus énervantes qu''un moustique');
INSERT INTO public.question (id, text) VALUES (54, 'Cite 3 raisons d''aller au mariage de ton crush');
INSERT INTO public.question (id, text) VALUES (55, 'Cite 3 moments ou c''est bon d''avoir mal');
INSERT INTO public.question (id, text) VALUES (56, 'Cite 3 raisons de dénoncer des sans papier');
INSERT INTO public.question (id, text) VALUES (57, 'Cite 3 techniques de fourbe pour la faire avaler');
INSERT INTO public.question (id, text) VALUES (58, 'Cite 3 contraceptifs aussi efficaces que la faciale');
INSERT INTO public.question (id, text) VALUES (59, 'Donne 3 raisons de t''assoir sur un tabouret à l''envers');
INSERT INTO public.question (id, text) VALUES (60, 'Donne 3 raisons de faire un piercing sur la langue');
INSERT INTO public.question (id, text) VALUES (61, 'Cite 3 lieux inappropriés pour faire l''amour');
INSERT INTO public.question (id, text) VALUES (62, 'Cite 3 lieux dangereux pour baiser');
INSERT INTO public.question (id, text) VALUES (63, 'Trouve 3 raisons de se raser le trou de balle');
INSERT INTO public.question (id, text) VALUES (64, 'Invente 3 façons de faire taire une féministe');
INSERT INTO public.question (id, text) VALUES (65, 'Donne 3 raisons de se faire couper un bout de verge');
INSERT INTO public.question (id, text) VALUES (66, 'Donne 3 raisons de jouer à "pince tétons" avec un pote');
INSERT INTO public.question (id, text) VALUES (88, 'Cite 3 bonnes raisons de ne pas porter de sous vêtements ');
INSERT INTO public.question (id, text) VALUES (67, 'Donne 3 raisons de partir en camping nudiste avec tes beaux parents');
INSERT INTO public.question (id, text) VALUES (68, 'Cite 3 raisons d''aller dans le nord pendant les vacances');
INSERT INTO public.question (id, text) VALUES (69, 'Cite 3 raisons de se faire masser par une meuf alors que tu as une copine');
INSERT INTO public.question (id, text) VALUES (70, 'Cite 3 films plus interessant qu''un rapport sexuel');
INSERT INTO public.question (id, text) VALUES (71, 'Cite 3 bonnes raisons de préférer le porno à ta copine');
INSERT INTO public.question (id, text) VALUES (72, 'Cite 3 personnes avec qui tu aimerais coucher');
INSERT INTO public.question (id, text) VALUES (73, 'Cite 3 avantages à avoir une petite bite');
INSERT INTO public.question (id, text) VALUES (74, 'Cite 3 animaux qui ne devrait pas exister');
INSERT INTO public.question (id, text) VALUES (75, 'Cite 3 cliché racistes');
INSERT INTO public.question (id, text) VALUES (76, 'Cite 3 présidents français');
INSERT INTO public.question (id, text) VALUES (77, 'Cite 3 raisons de te mettre en couple avec une shemale');
INSERT INTO public.question (id, text) VALUES (78, 'Cite 3 bonnes raisons de te faire circoncire');
INSERT INTO public.question (id, text) VALUES (79, 'Cite 3 catégorie pornographique');
INSERT INTO public.question (id, text) VALUES (80, 'Cite 3 bonnes raisons de devenir gay');
INSERT INTO public.question (id, text) VALUES (81, 'Cite 3 raisons de ne pas chier chez sa copine');
INSERT INTO public.question (id, text) VALUES (82, 'Cite 3 bonne raisons de brûler sa maison');
INSERT INTO public.question (id, text) VALUES (83, 'Cite 3 raisons de ne pas s''appeler Kévin');
INSERT INTO public.question (id, text) VALUES (84, 'Invente 3 prétexte pour larguer sa copine');
INSERT INTO public.question (id, text) VALUES (85, 'Cite 3 anecdotes inintéressantes sur toi');
INSERT INTO public.question (id, text) VALUES (86, 'Cite 3 raisons de ne pas sortir avec une moche');
INSERT INTO public.question (id, text) VALUES (89, 'Donne 3 raisons de prendre la pilule du lendemain');
INSERT INTO public.question (id, text) VALUES (90, 'Donne 3 raisons de ne pas utiliser de préservatif');
INSERT INTO public.question (id, text) VALUES (91, 'Donne 3 répliques de film');
INSERT INTO public.question (id, text) VALUES (92, 'Cite 3 excuses pour ne pas débarrasser la table');
INSERT INTO public.question (id, text) VALUES (93, 'Cite 3 moments opportuns pour faire l''hélicoptère');
INSERT INTO public.question (id, text) VALUES (94, 'Cite 3 choses que les hommes ne comprendrons jamais');
INSERT INTO public.question (id, text) VALUES (95, 'Cite 3 choses que les femmes ne comprendrons jamais');
INSERT INTO public.question (id, text) VALUES (96, 'Cite 3 raisons d''être curé');
INSERT INTO public.question (id, text) VALUES (97, 'Cite 3 choses que les hommes ferons toujours mieux que les femmes');
INSERT INTO public.question (id, text) VALUES (98, 'Cite 3 choses que les femmes ferons toujours mieux que les hommes');
INSERT INTO public.question (id, text) VALUES (99, 'Nomme 3 personnes que tu pousserais dans l''escalier');
INSERT INTO public.question (id, text) VALUES (100, 'Trouve 3 choses plus profondes que ton découvert bancaire');
INSERT INTO public.question (id, text) VALUES (102, 'Cite 2 choses plus étonnantes qu''un pénis sans testicules');
INSERT INTO public.question (id, text) VALUES (103, 'Cite 3 fluides qui peuvent hydrater le visage');
INSERT INTO public.question (id, text) VALUES (104, 'Nomme 3 personnes que tu aimerais voir réincarnées en papier toilette');
INSERT INTO public.question (id, text) VALUES (105, 'Cite 3 animaux de compagnie qui ne servent à rien');
INSERT INTO public.question (id, text) VALUES (107, 'Cite 3 moments ou il faut absolument sentir avant de lécher');
INSERT INTO public.question (id, text) VALUES (108, 'Donne 3 raisons de prendre un doigt dans le cul');
INSERT INTO public.question (id, text) VALUES (109, 'Donne 3 moment ou la taille sa compte');
INSERT INTO public.question (id, text) VALUES (110, 'Trouve 3 choses que tu aimes chez les gens du voyage');
INSERT INTO public.question (id, text) VALUES (111, 'Cite 3 nom courant de chienne');
INSERT INTO public.question (id, text) VALUES (112, 'Cite 3 utilisations possible d''un nain ');
INSERT INTO public.question (id, text) VALUES (113, 'Imagine 3 utilisations d''un tampon usagé');
INSERT INTO public.question (id, text) VALUES (114, 'Trouve 3 choses sur lesquelles dieu a merdé');
INSERT INTO public.question (id, text) VALUES (175, 'Cite 3 chansons pourries que tu adores écouter à fond seul chez toi');
INSERT INTO public.question (id, text) VALUES (176, 'Cite 3 chose à pas dire à une bonne sœur');
INSERT INTO public.question (id, text) VALUES (115, 'Cite les 3 choses que tu dis quand ça fini en 30 secondes');
INSERT INTO public.question (id, text) VALUES (116, 'Cite 3 professions qui sont tout le temps en grève');
INSERT INTO public.question (id, text) VALUES (117, 'Donne 3 synonymes de faire l''amour');
INSERT INTO public.question (id, text) VALUES (118, 'Cite 3 choses qui grossissent rapidement');
INSERT INTO public.question (id, text) VALUES (119, 'Cite 3 choses que tu dis quand tu vois un nouveau-né moche');
INSERT INTO public.question (id, text) VALUES (120, 'Cite 3 raisons d''éteindre la lumière pendant l''acte sexuelle');
INSERT INTO public.question (id, text) VALUES (121, 'Donne 3 défauts de ton EX');
INSERT INTO public.question (id, text) VALUES (122, 'Cite 3 choses à faire dans un lit');
INSERT INTO public.question (id, text) VALUES (123, 'Cite 3 outils qui servent à faire un trou');
INSERT INTO public.question (id, text) VALUES (124, 'Cite 3 choses qui font rêver un homme');
INSERT INTO public.question (id, text) VALUES (125, 'Cite 3 choses qu''on peut faire dans le noir');
INSERT INTO public.question (id, text) VALUES (126, 'Cite 3 lieux où on peut trouver beaucoup de monde');
INSERT INTO public.question (id, text) VALUES (127, 'Cite 3 choses que l''on peut trouver dans la poche avant d''une chemise');
INSERT INTO public.question (id, text) VALUES (128, 'Cite 3 accessoires juste pour les filles');
INSERT INTO public.question (id, text) VALUES (129, 'Cite 3 choses sur lesquelles on peut s''asseoir ');
INSERT INTO public.question (id, text) VALUES (130, 'Cite 3 endroits pour se relaxer');
INSERT INTO public.question (id, text) VALUES (131, 'Cite 3 trucs fluorescents');
INSERT INTO public.question (id, text) VALUES (132, 'Cite 3 moyens de déplacement non polluants');
INSERT INTO public.question (id, text) VALUES (8, 'Cite 3 expressions de racaille pour draguer');
INSERT INTO public.question (id, text) VALUES (106, 'Donne 3 choses aussi connes que de donner une grenade à un enfant de 5 ans');
INSERT INTO public.question (id, text) VALUES (133, 'Cite 3 trucs qui ne s''achètent pas');
INSERT INTO public.question (id, text) VALUES (134, 'Cite 3 trucs que t''as toujours sur toi');
INSERT INTO public.question (id, text) VALUES (135, 'Cite 3 choses qu''il faut avoir fait avant de mourir');
INSERT INTO public.question (id, text) VALUES (136, 'Cite 3 trucs qu''on peut charger');
INSERT INTO public.question (id, text) VALUES (137, 'Cite 3 raisons de préférer la copine de ton meilleur pote à la tienne');
INSERT INTO public.question (id, text) VALUES (138, 'Cite 3 choses qui t''excitent chez ton/ta partenaire');
INSERT INTO public.question (id, text) VALUES (139, 'Cite 3 endroits idéals dans la maison pour se faire pénétrer');
INSERT INTO public.question (id, text) VALUES (140, 'Cite 3 raisons de pratiquer les préliminaires au lieu d''une pénétration');
INSERT INTO public.question (id, text) VALUES (141, 'Cite 3 cadeaux en rapport avec le sexe');
INSERT INTO public.question (id, text) VALUES (142, 'Cite 3 endroits agréable où mettre un penis');
INSERT INTO public.question (id, text) VALUES (143, 'Cite 3 personnes célèbres sur qui tu fantasmes');
INSERT INTO public.question (id, text) VALUES (144, 'Cite 3 lieux les plus communs pour faire l''amour');
INSERT INTO public.question (id, text) VALUES (145, 'Cite 3 blessures possible lors d''un rapport sexuel');
INSERT INTO public.question (id, text) VALUES (146, 'Cite 3 raisons de ne pas coucher avec une personne inconnue');
INSERT INTO public.question (id, text) VALUES (147, 'Cite 3 synonymes de "seins"');
INSERT INTO public.question (id, text) VALUES (148, 'Cite 3 mots pour parler d''une chatte');
INSERT INTO public.question (id, text) VALUES (149, 'Cite 3 personnes de ton entourage avec qui tu pourrais coucher');
INSERT INTO public.question (id, text) VALUES (150, 'Cite 3 lieux inappropriés pour la masturbation');
INSERT INTO public.question (id, text) VALUES (151, 'Cite 3 endroits où tu as déjà fait l''amour');
INSERT INTO public.question (id, text) VALUES (152, 'Cite 3 pratiques sexuelles illégales');
INSERT INTO public.question (id, text) VALUES (153, 'Cite 3 liquides pouvant servir de lubrifiant');
INSERT INTO public.question (id, text) VALUES (154, 'Cite 3 choses qu''on peut trouver sur ta table de chevet');
INSERT INTO public.question (id, text) VALUES (155, 'Cite les 3 premières choses que tu fais quand tu te lèves');
INSERT INTO public.question (id, text) VALUES (156, 'Cite 3 objets longs et durs en forme de cylindre');
INSERT INTO public.question (id, text) VALUES (157, 'Cite 3 noms qu''on peut donner aux parties intime d''une homme');
INSERT INTO public.question (id, text) VALUES (158, 'Cite 3 méthodes contraceptives');
INSERT INTO public.question (id, text) VALUES (159, 'Cite 3 sujets source de disputes dans un couple');
INSERT INTO public.question (id, text) VALUES (160, 'Cite 3 trucs plus beaux que ton sexe');
INSERT INTO public.question (id, text) VALUES (161, 'Cite 3 positions sexuelles');
INSERT INTO public.question (id, text) VALUES (162, 'Cite 3 raisons de courir nu en forêt');
INSERT INTO public.question (id, text) VALUES (163, 'Cite 3 chose à faire avec du gravier');
INSERT INTO public.question (id, text) VALUES (164, 'Cite 3 animaux que tu aimes caresser');
INSERT INTO public.question (id, text) VALUES (165, 'Cite 3 façons rapide de faire de l''argent');
INSERT INTO public.question (id, text) VALUES (166, 'Imagine 3 goûts sympathiques pour un préservatif');
INSERT INTO public.question (id, text) VALUES (167, 'Cite 3 mots qui riment avec "sucer"');
INSERT INTO public.question (id, text) VALUES (168, 'Donne 3 sources de conflit dans un couple en voiture');
INSERT INTO public.question (id, text) VALUES (169, 'Donne 3 complexes courant chez les hommes');
INSERT INTO public.question (id, text) VALUES (170, 'Cite 3 chansons de Johnny');
INSERT INTO public.question (id, text) VALUES (171, 'Cite 3 choses qui peuvent provoquer la fin du monde');
INSERT INTO public.question (id, text) VALUES (172, 'Cite 3 choses que font les petits copains parfaits');
INSERT INTO public.question (id, text) VALUES (173, 'Donne 3 choses que tu retrouves dans un filtre de piscine publique');
INSERT INTO public.question (id, text) VALUES (174, 'Cite 3 raisons de se regarder dans le miroir');
INSERT INTO public.question (id, text) VALUES (177, 'Cite 3 bonnes raisons de rappeler ton ex.');
INSERT INTO public.question (id, text) VALUES (178, 'Cite 3 choses que tu aimerais avoir oublié');
INSERT INTO public.question (id, text) VALUES (179, 'Cite 3 accessoires pour une nuit torride ');
INSERT INTO public.question (id, text) VALUES (180, 'Cite 3 synonymes de "tu es sexy"');
INSERT INTO public.question (id, text) VALUES (181, 'Cite 3 raisons pour mettre des gants');
INSERT INTO public.question (id, text) VALUES (182, 'Cite 3 choses que tu peux faire avec ta main');
INSERT INTO public.question (id, text) VALUES (183, 'Cite 3 choses que tu peux faire avec ton pied');
INSERT INTO public.question (id, text) VALUES (184, 'Cite 3 raisons de te baigner nu(e)');
INSERT INTO public.question (id, text) VALUES (185, 'Cite 3 avantages de faire du vélo sans selle');
INSERT INTO public.question (id, text) VALUES (186, 'Trouve 3 raisons pour regarder une émission de Cyril Hanouna');
INSERT INTO public.question (id, text) VALUES (187, 'Cite 3 choses qui durcissent ');
INSERT INTO public.question (id, text) VALUES (188, 'Cite 3 choses que tu peux remuer');
INSERT INTO public.question (id, text) VALUES (189, 'Cite 3 moments où tu dois garder la bouche ouverte');
INSERT INTO public.question (id, text) VALUES (190, 'Cite 3 choses que l''on peut sucer');
INSERT INTO public.question (id, text) VALUES (191, 'Cite 3 choses que tu peux dire pendant un rapport sexuel et un déménagement');
INSERT INTO public.question (id, text) VALUES (192, 'Cite 3 choses que aimes avaler');
INSERT INTO public.question (id, text) VALUES (193, 'Cite 3 expressions que tu peux dire à un repas de famille et pendant l''amour');
INSERT INTO public.question (id, text) VALUES (194, 'Cite 3 plats avec du fromage');
INSERT INTO public.question (id, text) VALUES (195, 'Cite 3 choses qui gonflent');
INSERT INTO public.question (id, text) VALUES (196, 'Cite 3 choses que tu fais avant de faire l''amour');
INSERT INTO public.question (id, text) VALUES (197, 'Cite 3 choses à ne jamais faire dans une cours de récréation');
INSERT INTO public.question (id, text) VALUES (198, 'Cite 3 raisons valable d''aller en prison');
INSERT INTO public.question (id, text) VALUES (199, 'Cite 3 choses à ne pas faire avec les beaux parents');
INSERT INTO public.question (id, text) VALUES (200, 'Cite 3 choses que ne peut pas faire un manchot');
INSERT INTO public.question (id, text) VALUES (201, 'Cite 3 choses que tu peux faire dans une salle de bain');
INSERT INTO public.question (id, text) VALUES (202, 'Cite 3 choses que tu peux faire dans les toilettes');
INSERT INTO public.question (id, text) VALUES (203, 'Cite 3 choses que tu aimes malaxer');
INSERT INTO public.question (id, text) VALUES (204, 'Imagine 3 morts plus horribles que de se faire enterrer vivant');
INSERT INTO public.question (id, text) VALUES (205, 'Cite 3 déguisements improbables en soirée');
INSERT INTO public.question (id, text) VALUES (206, 'Cite 3 trucs qui t''explosent l''anus');
INSERT INTO public.question (id, text) VALUES (207, 'Cite 3 choses meilleures qu''un kebab en fin de soirée');
INSERT INTO public.question (id, text) VALUES (208, 'Cite 3 avantages d''être né dans une famille consanguine');
INSERT INTO public.question (id, text) VALUES (209, 'Cite 3 raisons pour lesquelles les migrants viennent en France');
INSERT INTO public.question (id, text) VALUES (210, 'Cite les 3 occupations principales d''un policier');
INSERT INTO public.question (id, text) VALUES (211, 'Cite 3 parties du corps que les femmes regardent chez les hommes');
INSERT INTO public.question (id, text) VALUES (212, 'Cite 3 choses qui quand elles sont secouées, jaillissent');
INSERT INTO public.question (id, text) VALUES (213, 'Cite 3 choses aussi rare qu''un Asiat bien monté');
INSERT INTO public.question (id, text) VALUES (214, 'Cite 3 façons de rendre son ex jalouse sur Facebook');
INSERT INTO public.question (id, text) VALUES (215, 'Donne 3 caractéristiques d''une belle poutre');
INSERT INTO public.question (id, text) VALUES (216, 'Cite 3 raisons d''être fonctionnaire');
INSERT INTO public.question (id, text) VALUES (217, 'Donne 3 raisons de choisir Android à iPhone');
INSERT INTO public.question (id, text) VALUES (218, 'Cite 3 manières de faire pleurer un enfant');
INSERT INTO public.question (id, text) VALUES (219, 'Cite 3 bonnes raisons de se prendre une cuite');
INSERT INTO public.question (id, text) VALUES (220, 'Donne 3 accessoires de la parfaite cagole marseillaise');
INSERT INTO public.question (id, text) VALUES (221, 'Cite 3 usages de tes doigts');
INSERT INTO public.question (id, text) VALUES (222, 'Dis 3 choses que tu as déjà volé à tes parents');
INSERT INTO public.question (id, text) VALUES (223, 'Cite 3 choses qui restent coincées entre les dents');
INSERT INTO public.question (id, text) VALUES (224, 'Complète de 3 façons : "21 cm c''est bien pour ..."');
INSERT INTO public.question (id, text) VALUES (225, 'Avoue 3 choses auxquelles tu ne peux pas résister');
INSERT INTO public.question (id, text) VALUES (226, 'Nomme 3 personnes illettrées ');
INSERT INTO public.question (id, text) VALUES (227, 'Cite 3 trucs que les femmes ne comprendront jamais');
INSERT INTO public.question (id, text) VALUES (228, 'Imite 3 cris d''orgasme différents');
INSERT INTO public.question (id, text) VALUES (229, 'Imite 3 cris pour faire peur à quelqu''un');
INSERT INTO public.question (id, text) VALUES (230, 'Cite 3 mots d''amour');
INSERT INTO public.question (id, text) VALUES (231, 'Cite 3 choses qu''on peut trouver dans ton frigo');
INSERT INTO public.question (id, text) VALUES (232, 'Cite 3 raisons de liker une meuf sur Tinder');
INSERT INTO public.question (id, text) VALUES (233, 'Cite 3 avantages d''être un homme par rapport à une femme');
INSERT INTO public.question (id, text) VALUES (234, 'Cite 3 expression de beauf');
INSERT INTO public.question (id, text) VALUES (235, 'Cite 3 prénoms de beaufs');
INSERT INTO public.question (id, text) VALUES (236, 'Donne 3 raisons d''accepter un plan à 3 avec ton/ta partenaire');
INSERT INTO public.question (id, text) VALUES (237, 'Donne 3 adjectifs pour décrire un pénis');
INSERT INTO public.question (id, text) VALUES (238, 'Cite 2 de tes fantasmes ');
INSERT INTO public.question (id, text) VALUES (239, 'Cite 3 personnes avec qui tu ne voudrais surtout pas coucher');
INSERT INTO public.question (id, text) VALUES (240, 'Cite 3 façons de pimenter ton couple');